### ISSUE TITLE
define functions in main file before use to compile on plaformio

### ISSUE THREAD

**Issue by AthenasArch** [noisymime/speeduino#1055]
the script not compiled when downloaded to the platformio, and the reason is that the functions in the main file were not defined at the beginning of the script, before using them.

**Comment by noisymime** [comment]
Have you loaded the whole project in PIO? 
The forward declarations are not specifically needed due to the way Arduino sketches are compiles, regardless of whether it's in the Arduino IDE or PlatformIO, though that can certainly be added for correctness. The code does definitely compile in PlatformIO in its current state though

**Comment by noisymime** [comment]
Closing as no response. PlatformIO compile working without issue
