### ISSUE TITLE
Bug: secondary spark table applies ignition corrections in multiply mode

### ISSUE THREAD

**Issue by adbancroft** [noisymime/speeduino#1154]
In multiply mode, we treat the values in the second spark table as percentages: the INI specifies a range of 0-215.

But `getAdvance2()` applies a couple of changes to the table value *before* it's used as a percentage:

1. Ignition offset - potentially making the value negative
2. Ignition advance corrections - which are degree based corrections.

Also worth noting that statuses::advance2 is int8_t, which doesn't have the range to store the range defined in the INI.

**Comment by adbancroft** [comment]
PR incoming...

**Comment by noisymime** [comment]
I've pushed up a quick fix for 2. making it so that the advance corrections are only performed when a switched mode is used. 

This doesn't fix the potential for a negative value, however I believe that can only occur in added mode if someone puts a negative value in the table. In multiply mode the smallest value you can get after subtracting `OFFSET_IGNITION` would be 0

**Comment by noisymime** [comment]
The added mode potential negative is addressed in #1155 and will be incorporated from there. I believe the changes of that occurring are fairly small.
