### ISSUE TITLE
Toyota 36-2 + 3 Decoder

### ISSUE THREAD

**Issue by ElDominio** [noisymime/speeduino#117]
Decoder for newer Toyotas, pending waveforms

**Comment by ElDominio** [comment]
[https://drive.google.com/open?id=1ZSCGGtc3eM9peHsCo4XzhE-S3thYAnit](url)

**Comment by ElDominio** [comment]
![whatsapp image 2017-11-29 at 12 15 25 am](https://user-images.githubusercontent.com/5685108/33357829-4200c800-d49b-11e7-9a88-5d18b3e33072.jpeg)

**Comment by xalejandro1** [comment]
hey guys, I have a 2ZZ already running, semi sequentially. I'd like support for this decoder so it can be run fully seuqntial, and I'm willing to test this code.

**Comment by ConnerMcLaughlin** [comment]
I made a pull request for my speeduino fork for completed code for this trigger wheel here: #120  Really the trigger wheel should be called 36-2/4-1 not 36-2+3 because it is essentially a missing tooth type trigger on primary with a missing tooth type trigger on secondary.  In other words it's a missing tooth dual wheel type.  How complete the code is is determined by the feedback of the testers.

**Comment by ConnerMcLaughlin** [comment]
...Oh to set it up you need to pick Missing tooth in the trigger pattern with 36 teeth and 2 missing then the extra setting of "Missing Tooth Secondary type" as 4-1 cam.  The rest of the setting the testers need to figure out.

**Comment by ConnerMcLaughlin** [comment]
https://github.com/ConnerMcLaughlin/speeduino/tree/36-2+3

**Comment by ElDominio** [comment]
Issue is resolved thanks to Conner. Works great on a Corolla XRS.

**Comment by noisymime** [comment]
PR #120 has been merged and adds this functionality.
