### ISSUE TITLE
2S staged injection does not appear to work. [$50]

### ISSUE THREAD

**Issue by TZ350** [noisymime/speeduino#162]
I have successfully bench tested 4S staged injection.  

But I plan on running my Speeduino V4 on a 2S and I  don't think things are working properly in staged 2S mode. The secondary injector does not come on at all and the pulse width is an impossible 8ms when the maximum time for a 2S at 12k rpm is < 5ms.

![12k should be less than 5ms](https://user-images.githubusercontent.com/43022326/45193151-c38b5500-b2a0-11e8-9e83-7a26fe085af8.jpg)
![2s staged but only primary injector active](https://user-images.githubusercontent.com/43022326/45193152-c423eb80-b2a0-11e8-8b77-70924fe96495.jpg)

**Comment by noisymime** [comment]
Please post the tune you're using for this. 

Do you have sequential enabled as that could explain the greater than 5ms pulsewidth, otherwise it does look to be a bug

**Comment by TZ350** [comment]
I don't seem to be able to upload the Current Tune msq file to here but here is a link to where I uploaded it on my Speeduino projects thread.


https://speeduino.com/forum/download/file.php?id=3736

**Comment by noisymime** [comment]
OK, there's a few things going on here. In short the issue comes down to a configuration that admittedly I hadn't tested on. Specifically, 1 cylinder, sequential 2 stroke with staging (Though the same would apply to 2 cylinder, sequential 2 stroke. But NOT 3 or more cylinders or 4 strokes). 

For obvious reasons, only 1 or 2 cylinder engines are supported with sequential and staging (Due to there only being 4 injector outputs). The staging calculation checks whether you're running sequential or not and doubles the allowable pulse width if you are. At this point in the calcs there should be a check that only performs that if it's a 4 stroke engine, but this is not currently there. 

The upshot is that the system thinks it has around 10ms for the injection (2 crank revolutions) when it actually only has one due to it being a 2 stroke. This is why you're seeing an 8ms pulse width and the secondary injection is never coming on. 

I'll get this addressed shortly as it should be a simple fix.

**Comment by TZ350** [comment]
Great, Thank you.

**Comment by noisymime** [comment]
If you can, are you able to give the current github code a try? (You can grab a snapshot at: https://github.com/noisymime/speeduino/archive/master.zip)

**Comment by TZ350** [comment]
Yes, will do as soon as I get home from work tonight.

**Comment by TZ350** [comment]
Hi Josh. Yes compiled and ran the current github code along with loading the Speedino ini file into tuning Studeo. The pulse width is good at 4.5ms at 12k rpm and with the max pulse width set at 80% the pulse width gauge maxis out at 40% . The secondary injector still does not light up.

![12k rpm pulse width 4-5ms](https://user-images.githubusercontent.com/43022326/45214522-cf056d00-b2ee-11e8-9a14-83a5840bd160.jpg)
![only the primary lights up](https://user-images.githubusercontent.com/43022326/45214524-d0369a00-b2ee-11e8-8193-65bc873bb270.jpg)
![12k rpm pulse width 4-5ms](https://user-images.githubusercontent.com/43022326/45214599-f6f4d080-b2ee-11e8-9444-f5fb94b22de5.jpg)

![only the primary lights up](https://user-images.githubusercontent.com/43022326/45214600-f78d6700-b2ee-11e8-9d6b-3a97bb1fea30.jpg)

**Comment by noisymime** [comment]
Ahh, I just realised something that may not be obvious on a 1 cylinder staged setup. The secondary output will be on injector 3, not injector 2. 

She  using staging, the inj1 and inj2 outputs are both considered the primaries and inj3 and inj4 the corresponding secondaries. Try switching your secondary to inj3.

I'll make a table documenting this on the wiki

**Comment by TZ350** [comment]
Hi Josh I have tried your suggestion. Primary injector on pin 1 and secondary injector on pin 3 but the secondary does not light up. The LED tested Ok. Rob.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by TZ350** [comment]
.
Secondary injector still does not light up.
Pulse width is Ok now at 12k rpm.
Duty Cycle is only indicating half of what it should be. 4ms @ 12k = 80%

![12k rpm pulse width 4-5ms](https://user-images.githubusercontent.com/43022326/45258115-6e695380-b406-11e8-8c90-13b24136d2af.jpg)
![only the primary injector is lighting up](https://user-images.githubusercontent.com/43022326/45258116-6f01ea00-b406-11e8-8606-404e57fc2300.jpg)

**Comment by TZ350** [comment]
.
Staged injection still does not work on 1 cyl & 2 cyl two stroke.
.

**Comment by TZ350** [comment]
.
Single cylinder two stroke staged injection looks to be working. A few tests to do but looking good.  

![staged inj and fuel pump](https://user-images.githubusercontent.com/43022326/45542662-a9d0ab80-b866-11e8-9bcf-5de6c06cd3d7.jpg)
